#!/usr/bin/python

import requests, sys, etcs2ly

data = requests.get("http://127.0.0.1:5000/kjsong/api/v1.0/tune/%s/stripped" % sys.argv[1]).json()
kwargs = {s[0]: s[1].strip('"') for s in [a.split('=') for a in sys.argv[2:]]}
kwargs['startpos'],best_key = etcs2ly.detect_startpos(data['codes'], kwargs['startpos'] if 'startpos' in kwargs else None)
if 'key' not in kwargs:
    kwargs['key'] = best_key
if 'instr' in kwargs:
    kwargs['instr'] = kwargs['instr'].replace('_', ' ')
print (etcs2ly.etcs2ly(data, **kwargs))
