#!/bin/bash

$(dirname ${BASH_SOURCE[0]})/../api/txt2jtuneparsepost < ${1} > /tmp/kjsong${$}.json
[ -z $CMD ] && CMD=POST
curl -i -H "Content-Type: application/json" -d @/tmp/kjsong${$}.json -X ${CMD} http://127.0.0.1:5000/kjsong/api/v1.0/tune
