#!/usr/bin/python

import sys, kjwstat

cnx = kjwstat.db_maintain_connect()
harmonies = [[]]
for line in sys.stdin:
    line=line[0:-1]
    if line=='===':
        harmonies.append([])
    else:
        harmonies[-1].append(line.split())
for harmony in harmonies:
    if harmony:
        kjwstat.store_harmony(cnx, harmony)
cnx.commit()
cnx.close()
