#!/usr/bin/python

import sys, kjwstat

cnx = kjwstat.db_maintain_connect()
melodies = [[]]
for line in sys.stdin:
    line=line[0:-1]
    if line=='===':
        melodies.append([])
    else:
        melodies[-1].append(line.split())
for melody in melodies:
    if melody:
        kjwstat.store_melody(cnx, melody[1:], melody[0][0])
cnx.commit()
cnx.close()
