#!/usr/bin/python

from kjwstat import *
import sys

if len(sys.argv)<3:
    print("usage: %s TEXT METRE [LANG]" % sys.argv[0])
    exit(1)
    
text=sys.argv[1]
lang=sys.argv[3] if len(sys.argv)>3 else 'eng'
metre=sys.argv[2]

cnx = db_maintain_connect()
ldict = get_lang_dict(cnx, lang)
cnx.close()
print(detect_verse_feets(text, metre, lang, ldict))
