#!/bin/bash

CMD=PATCH
NAME=name
urlencode() {
    # urlencode <string>

    local length="${#1}"
    for (( i = 0; i < length; i++ )); do
        local c="${1:i:1}"
        case $c in
            [a-zA-Z0-9.~_-\;]) printf "$c" ;;
            *) printf '%s' "$c" | xxd -p -c1 |
                   while read c; do printf '%%%s' "$c"; done ;;
        esac
    done
}

NAME_TO_USE=`urlencode "${2}"`

curl -i -X ${CMD} "http://127.0.0.1:5000/kjsong/api/v1.0/person/${1}/${NAME}/${NAME_TO_USE}"
