#!/usr/bin/python

import requests, sys, kjwtxt

if len(sys.argv) != 2:
    data = requests.get("http://127.0.0.1:5000/kjsong/api/v1.0/tune").json()
    try:
        print ('\n'.join(kjwtxt.kjtunes_to_txt_vec(data)))
    except:
        print (kjwtxt.kjtunes_to_txt_vec(data))
else:
    data = requests.get("http://127.0.0.1:5000/kjsong/api/v1.0/tune/%s/stripped" % sys.argv[1]).json()
    print ('\n'.join(kjwtxt.kjtune_to_txt_vec(data)))
